#!/bin/sh

SRCFILE="$1"
DSTDIR="$2"
DSTFILE="$DSTDIR/$3"

# echo "Creating $DSTDIR if it doesn't already exist.."
mkdir -p $DSTDIR

# echo "Processing $SRCFILE -> $DSTFILE"

cat <<HEADER > $DSTFILE
<html>
<head>
<style type="text/css">
h1 { font-size: 1.2em }
h2 { font-size: 1.1em }
body { font-family: sans-serif; }
</style>
</head>
<body>
HEADER

$SRCROOT/Scripts/Markdown.pl $SRCFILE >> $DSTFILE

cat <<FOOTER >> $DSTFILE
</body>
</html>
FOOTER
