#!/bin/sh

SRCFILE="$1"
DSTDIR="$2"
DSTFILE="$DSTDIR/$3"

echo "Creating $DSTDIR if it doesn't already exist.."
mkdir -p $DSTDIR

echo "Processing $SRCFILE.."
echo " -> $DSTFILE"

cat <<HEADER > $DSTFILE
<html>
<head>
<style type="text/css">
body { font-family: sans-serif; }
</style>
</head>
<body>
HEADER

$SRCROOT/Scripts/Markdown.pl $SRCFILE >> $DSTFILE

cat <<FOOTER >> $DSTFILE
</body>
</html>
FOOTER
